### ISSUE TITLE
Drzewo lokalizacji.

### ISSUE THREAD

**Issue by fmatuszewski** [ParticipatoryBudgeting/MyCommunity#6]
Drzewo lokalizacji zawiera zarówno miasta jak i dzielnice w jednej liście rozwijanej.
Chciałbym aby zastąpić tą listę jakimś drzewem rozwijanym.
Po rozwinięciu menu widoczne były by tylko miasta.
Po kliknięciu [+] z lewej strony miasta są rozwijane (wyświetlane ) dzielnice tego miasta pod miastem tak jak jest to zrobione teraz.

**Comment by mat3k** [comment]
Aktualne rozwiązanie jest wystarczające ?

**Comment by fmatuszewski** [comment]
Jest ok
